
/**
 * Color scale generated by http://colorbrewer2.org. 
 */
const redScale = ['#fff5f0','#fee0d2','#fcbba1','#fc9272','#fb6a4a','#ef3b2c','#cb181d','#99000d']
const blueScale = ['#fff7fb','#ece7f2','#d0d1e6','#a6bddb','#74a9cf','#3690c0','#0570b0','#034e7b']
const greenScale = ['#f7fcf5','#e5f5e0','#c7e9c0','#a1d99b','#74c476','#41ab5d','#238b45','#005a32']
const purpleScale = ['#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177']

const getColorScale = (colorName) => {
  switch (colorName) {
    case "red":
      return redScale
    case "blue":
      return blueScale
    case "green":
      return greenScale
    case "purble":
      return purpleScale
    default:
      return redScale
  }
}

/* Returns a color assignment function `(val) -> hex string` */
const ColorAssignment = (colorName, rangeMin, rangeMax) => {
  let scale = getColorScale(colorName);
  let interval = (rangeMax - rangeMin) / scale.length;
  return (val) => {
    return scale[Math.floor(val / interval)]
  };
}

export default ColorAssignment;